name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main # Or your desired branch
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/OwenTanKL/resume-evaluator
          git remote set-url space https://OwenTanKL:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/OwenTanKL/resume-evaluator
          git push --force space main
